import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { evaluate } from '@marcbachmann/cel-js';
import type { V1Container, V1Namespace, V1Pod } from '@kubernetes/client-node';
import fc from 'fast-check';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { parseAllDocuments } from 'yaml';
import { ALL_CHECKS } from '../src/checks/index.js';
import { main } from '../src/cli.js';
import { CEL_RULES, NOT_ADMISSION_SHAPED, policyDocuments, renderPolicies } from '../src/policy.js';
import { loadDemoSnapshot } from '../src/scan.js';
import { hardenedPod, snap, snapshotFromMisconfigFixtures } from './helpers.js';

type Doc = { kind: string; metadata: { name: string }; spec: Record<string, any> }; // eslint-disable-line @typescript-eslint/no-explicit-any

const docs = (opts = {}) => policyDocuments(opts) as Doc[];
const policies = () => docs().filter((d) => d.kind === 'ValidatingAdmissionPolicy');

/** Evaluate a generated policy the way the API server does: variables first, then the validation. */
function admits(policy: Doc, object: unknown, request = { operation: 'CREATE', subResource: '' }, oldObject: unknown = null): boolean {
  const variables: Record<string, unknown> = {};
  const ctx = { object, oldObject, variables, request };
  for (const v of (policy.spec.variables ?? []) as Array<{ name: string; expression: string }>) variables[v.name] = evaluate(v.expression, ctx);
  return (policy.spec.validations as Array<{ expression: string }>).every((x) => evaluate(x.expression, ctx) === true);
}

const byId = (id: string) => policies().find((p) => p.metadata.name === id.toLowerCase())!;
const passesCheck = (id: string, pod: V1Pod) => ALL_CHECKS.find((c) => c.id === id)!.run(snap({ pods: [pod] }), { excludedNamespaces: new Set() }).length === 0;
const asPod = (p: V1Pod) => ({ apiVersion: 'v1', kind: 'Pod', ...p });
const POD_RULES = Object.keys(CEL_RULES).filter((id) => id.startsWith('NOIP-POD-'));

describe('policy export', () => {
  it('covers every admission-shaped check and names the rest', () => {
    expect(Object.keys(CEL_RULES).sort()).toEqual(ALL_CHECKS.map((c) => c.id).filter((id) => /POD-|NS-/.test(id)).sort());
    expect(NOT_ADMISSION_SHAPED).toEqual(['NOIP-NET-001', 'NOIP-NET-002', 'NOIP-RBAC-001', 'NOIP-RBAC-002', 'NOIP-RBAC-003']);
    expect(policies()).toHaveLength(10);
    expect(docs().filter((d) => d.kind === 'ValidatingAdmissionPolicyBinding')).toHaveLength(10);
  });

  it('defaults to Warn+Audit that never blocks, and --action deny fails closed', () => {
    const b = docs().find((d) => d.kind === 'ValidatingAdmissionPolicyBinding')!;
    expect(b.spec.validationActions).toEqual(['Warn', 'Audit']);
    expect(policies()[0]!.spec.failurePolicy).toBe('Ignore');
    const deny = docs({ action: 'deny' });
    expect(deny.find((d) => d.kind === 'ValidatingAdmissionPolicyBinding')!.spec.validationActions).toEqual(['Deny']);
    expect(deny.find((d) => d.kind === 'ValidatingAdmissionPolicy')!.spec.failurePolicy).toBe('Fail');
    expect(docs({ action: 'audit' }).find((d) => d.kind === 'ValidatingAdmissionPolicyBinding')!.spec.validationActions).toEqual(['Audit']);
  });

  it('filters by check and severity, and scopes namespaces', () => {
    expect(docs({ minSeverity: 'critical' }).map((d) => d.metadata.name)).toEqual(['noip-pod-001', 'noip-pod-001', 'noip-pod-002', 'noip-pod-002']);
    expect(docs({ checks: ['NOIP-POD-004'] })).toHaveLength(2);
    expect(() => docs({ checks: ['NOIP-NET-001'] })).toThrow(/not expressible/);
    expect(() => docs({ checks: ['NOPE'] })).toThrow(/unknown check/);
    expect(() => docs({ excludeNamespaces: ["x'] || true || ['"] })).toThrow(/invalid namespace/);
    const scoped = docs({ excludeNamespaces: ['ci'] });
    expect(scoped.find((d) => d.kind === 'ValidatingAdmissionPolicyBinding')!.spec.matchResources.namespaceSelector.matchExpressions[0].values).toEqual(['ci', 'kube-node-lease', 'kube-public', 'kube-system']);
    const all = docs({ includeSystemNamespaces: true, checks: ['NOIP-POD-001', 'NOIP-NS-001'] });
    expect(all[1]!.spec.matchResources).toEqual({ namespaceSelector: {} });
    expect(all[2]!.spec.matchConditions).toBeUndefined();
  });

  it('renders multi-document YAML that parses back, with a header saying what it does', () => {
    const y = renderPolicies();
    expect(y).toMatch(/^# Generated by `noip policy`/);
    expect(y).toContain('Warn + Audit (nothing is blocked)');
    expect(renderPolicies({ action: 'deny' })).toContain('Deny (non-compliant requests are rejected)');
    expect(renderPolicies({ action: 'audit' })).toContain('Audit (annotations in the audit log only)');
    const parsed = parseAllDocuments(y).map((d) => d.toJS() as Doc);
    expect(parsed).toEqual(docs());
  });
});

describe('CEL rules agree with the checks', () => {
  it('on the demo cluster and the seeded misconfig fixtures', () => {
    const pods = [...loadDemoSnapshot().pods, ...snapshotFromMisconfigFixtures().pods, hardenedPod()];
    for (const id of POD_RULES) for (const pod of pods) expect(admits(byId(id), asPod(pod)), `${id} on ${pod.metadata?.name}`).toBe(passesCheck(id, pod));
  });

  const dns = fc.stringMatching(/^[a-z][a-z0-9-]{0,8}$/);
  const maybe = <T>(a: fc.Arbitrary<T>) => fc.option(a, { nil: undefined });
  const container = fc.record(
    {
      name: dns,
      image: fc.constant('img'),
      securityContext: maybe(
        fc.record(
          {
            privileged: fc.boolean(),
            allowPrivilegeEscalation: fc.boolean(),
            readOnlyRootFilesystem: fc.boolean(),
            runAsNonRoot: fc.boolean(),
            runAsUser: fc.constantFrom(0, 1, 1000, 65534),
          },
          { requiredKeys: [] },
        ),
      ),
      resources: maybe(fc.record({ limits: maybe(fc.record({ cpu: fc.constant('100m'), memory: fc.constant('64Mi') }, { requiredKeys: [] })) }, { requiredKeys: [] })),
      env: maybe(fc.array(fc.record({ name: dns, valueFrom: maybe(fc.record({ secretKeyRef: maybe(fc.record({ name: dns, key: dns })) }, { requiredKeys: [] })) }, { requiredKeys: ['name'] }), { maxLength: 2 })),
      envFrom: maybe(fc.array(fc.record({ secretRef: maybe(fc.record({ name: dns })), configMapRef: maybe(fc.record({ name: dns })) }, { requiredKeys: [] }), { maxLength: 2 })),
    },
    { requiredKeys: ['name', 'image'] },
  ) as unknown as fc.Arbitrary<V1Container>;
  const pod = fc.record({
    metadata: fc.record({ name: dns, namespace: fc.constant('app') }),
    spec: fc.record(
      {
        hostPID: fc.boolean(),
        hostIPC: fc.boolean(),
        hostNetwork: fc.boolean(),
        securityContext: fc.record({ runAsNonRoot: fc.boolean(), runAsUser: fc.constantFrom(0, 1000) }, { requiredKeys: [] }),
        initContainers: fc.uniqueArray(container, { selector: (c) => c.name, maxLength: 1 }),
        ephemeralContainers: fc.uniqueArray(container, { selector: (c) => c.name, maxLength: 1 }),
        containers: fc.uniqueArray(container, { selector: (c) => c.name, minLength: 1, maxLength: 2 }),
      },
      { requiredKeys: ['containers'] },
    ),
  }) as unknown as fc.Arbitrary<V1Pod>;

  it('on random pods (property)', () => {
    fc.assert(
      fc.property(pod, (p) => {
        for (const id of POD_RULES) expect(admits(byId(id), asPod(p)), id).toBe(passesCheck(id, p));
      }),
      { numRuns: 400 },
    );
  });

  it('reads the pod template of every workload kind', () => {
    fc.assert(
      fc.property(pod, fc.constantFrom('Deployment', 'StatefulSet', 'DaemonSet', 'ReplicaSet', 'Job', 'CronJob'), (p, kind) => {
        const spec = { ...p.spec! };
        delete spec.ephemeralContainers; // not part of a pod template
        const template = { metadata: {}, spec };
        const object = kind === 'CronJob' ? { kind, spec: { jobTemplate: { spec: { template } } } } : { kind, spec: { template } };
        for (const id of POD_RULES) expect(admits(byId(id), object), `${id} ${kind}`).toBe(passesCheck(id, { ...p, spec }));
      }),
      { numRuns: 100 },
    );
  });

  it('pods are matched on CREATE only; kubectl debug is checked on the ephemeralcontainers subresource', () => {
    for (const p of policies().filter((x) => x.metadata.name.startsWith('noip-pod-'))) {
      const rules = p.spec.matchConstraints.resourceRules as Array<{ resources: string[]; operations: string[] }>;
      expect(rules.find((r) => r.resources.includes('pods'))!.operations).toEqual(['CREATE']);
      const eph = rules.find((r) => r.resources.includes('pods/ephemeralcontainers'));
      expect(Boolean(eph), p.metadata.name).toBe(!['noip-pod-002', 'noip-pod-003', 'noip-pod-004', 'noip-pod-008'].includes(p.metadata.name));
    }
    // An old pod without limits/securityContext can still get a hardened debug container…
    const legacy = asPod({ metadata: { name: 'old', namespace: 'app' }, spec: { containers: [{ name: 'app', image: 'x' }] } });
    const hardenedDebug = { name: 'dbg', image: 'busybox', securityContext: { privileged: false, allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, runAsNonRoot: true } };
    const sub = { operation: 'UPDATE', subResource: 'ephemeralcontainers' };
    const withDebug = (c: object) => ({ ...legacy, spec: { ...legacy.spec, ephemeralContainers: [c] } });
    for (const id of ['NOIP-POD-001', 'NOIP-POD-005', 'NOIP-POD-006', 'NOIP-POD-007', 'NOIP-POD-009']) expect(admits(byId(id), withDebug(hardenedDebug), sub), id).toBe(true);
    // …but a privileged one is flagged, and the regular containers are still checked on CREATE.
    expect(admits(byId('NOIP-POD-001'), withDebug({ ...hardenedDebug, securityContext: { privileged: true } }), sub)).toBe(false);
    // Review 4: an old privileged debug container (can't be removed) must not block a later, hardened one.
    const old = withDebug({ ...hardenedDebug, name: 'old', securityContext: { privileged: true } });
    const next = { ...old, spec: { ...old.spec, ephemeralContainers: [...old.spec.ephemeralContainers, { ...hardenedDebug, name: 'new' }] } };
    expect(admits(byId('NOIP-POD-001'), next, sub, old)).toBe(true);
    const nextBad = { ...old, spec: { ...old.spec, ephemeralContainers: [...old.spec.ephemeralContainers, { ...hardenedDebug, name: 'new', securityContext: { privileged: true } }] } };
    expect(admits(byId('NOIP-POD-001'), nextBad, sub, old)).toBe(false);
    expect(admits(byId('NOIP-POD-007'), withDebug(hardenedDebug))).toBe(false);
  });

  it('namespace rule matches NOIP-NS-001, and system namespaces are excluded by a match condition', () => {
    const ns = byId('NOIP-NS-001');
    const check = ALL_CHECKS.find((c) => c.id === 'NOIP-NS-001')!;
    for (const labels of [undefined, {} as Record<string, string>, { 'pod-security.kubernetes.io/enforce': 'restricted' }, { 'pod-security.kubernetes.io/enforce': 'baseline' }, { 'pod-security.kubernetes.io/enforce': 'privileged' }]) {
      const n: V1Namespace = { metadata: { name: 'x', ...(labels ? { labels } : {}) } };
      expect(admits(ns, n)).toBe(check.run(snap({ namespaces: [n] }), { excludedNamespaces: new Set() }).length === 0);
    }
    const cond = ns.spec.matchConditions[0].expression as string;
    expect(evaluate(cond, { object: { metadata: { name: 'kube-system' } } })).toBe(false);
    expect(evaluate(cond, { object: { metadata: { name: 'shop' } } })).toBe(true);
  });
});

describe('noip policy subcommand', () => {
  let out = '';
  let err = '';
  beforeEach(() => {
    out = '';
    err = '';
    vi.spyOn(process.stdout, 'write').mockImplementation((s) => ((out += String(s)), true));
    vi.spyOn(process.stderr, 'write').mockImplementation((s) => ((err += String(s)), true));
  });
  afterEach(() => {
    vi.restoreAllMocks();
    process.exitCode = undefined;
  });

  it('prints YAML, writes a file, and reports bad check IDs as an error', async () => {
    await main(['node', 'noip', 'policy', '--min-severity', 'high']);
    expect(out).toContain('name: noip-pod-004');
    expect(out).not.toContain('noip-pod-005');
    expect(err).toContain('policy: 5 ValidatingAdmissionPolicy + binding pair(s), action warn');
    const f = join(mkdtempSync(join(tmpdir(), 'noip-policy-')), 'p.yaml');
    await main(['node', 'noip', 'policy', '--action', 'deny', '--checks', 'NOIP-POD-001', '--exclude-namespace', 'ci', '--include-system', '--out', f]);
    expect(readFileSync(f, 'utf8')).toContain('- Deny');
    await main(['node', 'noip', 'policy', '--checks', 'NOIP-RBAC-001']);
    expect(process.exitCode).toBe(1);
    expect(err).toContain('not expressible as an admission policy: NOIP-RBAC-001');
  });
});
